(function(){var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<
a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}};da("globalThis",function(a){return a||ca});
da("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self,n=function(a,b){a=a.split(".");var c=e;a[0]in c||typeof c.execScript=="undefined"||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var q=new Map([]);q.set("devsite-a11y-announce",{src:"/android/js/devsite_devsite_a11y_announce_module.js"});q.set("devsite-actions",{src:"/android/js/devsite_devsite_actions_module.js"});q.set("devsite-activity-tracker",{src:"/android/js/devsite_devsite_activity_tracker_module.js"});q.set("devsite-analytics",{src:"/android/js/devsite_devsite_analytics_module.js"});q.set("devsite-analytics-scope",{src:"/android/js/devsite_devsite_analytics_scope_module.js"});q.set("devsite-anselm",{src:"/android/js/devsite_devsite_anselm_module.js"});
q.set("devsite-api-getstarted",{src:"/android/js/devsite_devsite_api_getstarted_module.js"});q.set("devsite-apix",{src:"/android/js/devsite_devsite_apix_module.js"});q.set("devsite-apix-index",{src:"/android/js/devsite_devsite_apix_index_module.js"});q.set("devsite-apix-snippets",{src:"/android/js/devsite_devsite_apix_snippets_module.js"});q.set("devsite-appearance-selector",{src:"/android/js/devsite_devsite_appearance_selector_module.js"});q.set("devsite-author-page-insights",{src:"/android/js/devsite_devsite_author_page_insights_module.js"});
q.set("devsite-badge-awarded",{src:"/android/js/devsite_devsite_badge_awarded_module.js"});q.set("devsite-badge-awarder",{src:"/android/js/devsite_devsite_badge_awarder_module.js"});q.set("devsite-badge-redeemer",{src:"/android/js/devsite_devsite_badge_redeemer_module.js"});q.set("devsite-badger",{src:"/android/js/devsite_devsite_badger_module.js"});q.set("devsite-book-nav",{src:"/android/js/devsite_devsite_book_nav_module.js"});q.set("devsite-bookmark",{src:"/android/js/devsite_devsite_bookmark_module.js"});
q.set("devsite-carousel",{src:"/android/js/devsite_devsite_carousel_module.js"});q.set("devsite-catalog",{src:"/android/js/devsite_devsite_catalog_module.js"});q.set("devsite-catalog-body-badges",{src:"/android/js/devsite_devsite_catalog_body_badges_module.js"});q.set("devsite-chart",{src:"/android/js/devsite_devsite_chart_module.js"});q.set("devsite-checkbox",{src:"/android/js/devsite_devsite_checkbox_module.js"});q.set("devsite-chip",{src:"/android/js/devsite_devsite_chip_module.js"});
q.set("devsite-code",{src:"/android/js/devsite_devsite_code_module.js"});q.set("devsite-codelab-catalog",{src:"/android/js/devsite_devsite_codelab_catalog_module.js"});q.set("devsite-concierge",{src:"/android/js/devsite_devsite_concierge_module.js"});q.set("devsite-concierge-ai-panel",{src:"/android/js/devsite_devsite_concierge_ai_panel_module.js"});q.set("devsite-concierge-api-explorer-panel",{src:"/android/js/devsite_devsite_concierge_api_explorer_panel_module.js"});
q.set("devsite-concierge-apix",{src:"/android/js/devsite_devsite_concierge_apix_module.js"});q.set("devsite-concierge-info-panel",{src:"/android/js/devsite_devsite_concierge_info_panel_module.js"});q.set("devsite-concierge-my-activity-panel",{src:"/android/js/devsite_devsite_concierge_my_activity_panel_module.js"});q.set("devsite-concierge-recommendations-panel",{src:"/android/js/devsite_devsite_concierge_recommendations_panel_module.js"});q.set("devsite-content",{src:"/android/js/devsite_devsite_content_module.js"});
q.set("devsite-content-excellence",{src:"/android/js/devsite_devsite_content_excellence_module.js"});q.set("devsite-content-stepper",{src:"/android/js/devsite_devsite_content_stepper_module.js"});q.set("devsite-cookie-notification-bar",{src:"/android/js/devsite_devsite_cookie_notification_bar_module.js"});q.set("devsite-countdown",{src:"/android/js/devsite_devsite_countdown_module.js"});q.set("devsite-credentials-dialog",{src:"/android/js/devsite_devsite_credentials_dialog_module.js"});
q.set("devsite-cse",{src:"/android/js/devsite_devsite_cse_module.js"});q.set("devsite-device",{src:"/android/js/devsite_devsite_device_module.js"});q.set("devsite-devprofile",{src:"/android/js/devsite_devsite_devprofile_module.js"});q.set("devsite-dialog",{src:"/android/js/devsite_devsite_dialog_module.js"});q.set("devsite-dropdown-list",{src:"/android/js/devsite_devsite_dropdown_list_module.js"});q.set("devsite-dynamic-content",{src:"/android/js/devsite_devsite_dynamic_content_module.js"});
q.set("devsite-dynamic-hero",{src:"/android/js/devsite_devsite_dynamic_hero_module.js"});q.set("devsite-edit-profile",{src:"/android/js/devsite_devsite_edit_profile_module.js"});q.set("devsite-engedu-telemetry",{src:"/android/js/devsite_devsite_engedu_telemetry_module.js"});q.set("devsite-expandable",{src:"/android/js/devsite_devsite_expandable_module.js"});q.set("devsite-extradory",{src:"/android/js/devsite_devsite_extradory_module.js"});q.set("devsite-fast-track-profile-creator",{src:"/android/js/devsite_devsite_fast_track_profile_creator_module.js"});
q.set("devsite-feature-tooltip",{src:"/android/js/devsite_devsite_feature_tooltip_module.js"});q.set("devsite-feedback",{src:"/android/js/devsite_devsite_feedback_module.js"});q.set("devsite-filter",{src:"/android/js/devsite_devsite_filter_module.js"});q.set("devsite-footer-linkboxes",{src:"/android/js/devsite_devsite_footer_linkboxes_module.js"});q.set("devsite-footer-promos",{src:"/android/js/devsite_devsite_footer_promos_module.js"});q.set("devsite-footer-utility",{src:"/android/js/devsite_devsite_footer_utility_module.js"});
q.set("devsite-fully-clickable",{src:"/android/js/devsite_devsite_fully_clickable_module.js"});q.set("devsite-googler-buttons",{src:"/android/js/devsite_devsite_googler_buttons_module.js"});q.set("devsite-hats-survey",{src:"/android/js/devsite_devsite_hats_survey_module.js"});q.set("devsite-header",{src:"/android/js/devsite_devsite_header_module.js"});q.set("devsite-heading-link",{src:"/android/js/devsite_devsite_heading_link_module.js"});q.set("devsite-iframe",{src:"/android/js/devsite_devsite_iframe_module.js"});
q.set("devsite-info-popout",{src:"/android/js/devsite_devsite_info_popout_module.js"});q.set("devsite-interests",{src:"/android/js/devsite_devsite_interests_module.js"});q.set("devsite-jsfiddle-button",{src:"/android/js/devsite_devsite_jsfiddle_button_module.js"});q.set("devsite-json-validator",{src:"/android/js/devsite_devsite_json_validator_module.js"});q.set("devsite-jump-to",{src:"/android/js/devsite_devsite_jump_to_module.js"});q.set("devsite-key-takeaways",{src:"/android/js/devsite_devsite_key_takeaways_module.js"});
q.set("devsite-language-selector",{src:"/android/js/devsite_devsite_language_selector_module.js"});q.set("devsite-lightbox",{src:"/android/js/devsite_devsite_lightbox_module.js"});q.set("devsite-mathjax",{src:"/android/js/devsite_devsite_mathjax_module.js"});q.set("devsite-multiple-choice",{src:"/android/js/devsite_devsite_multiple_choice_module.js"});q.set("devsite-mwc",{src:"/android/js/devsite_devsite_mwc_module.js"});q.set("devsite-my-activity-light",{src:"/android/js/devsite_devsite_my_activity_light_module.js"});
q.set("devsite-my-community",{src:"/android/js/devsite_devsite_my_community_module.js"});q.set("devsite-nav-buttons",{src:"/android/js/devsite_devsite_nav_buttons_module.js"});q.set("devsite-notification",{src:"/android/js/devsite_devsite_notification_module.js"});q.set("devsite-pagination",{src:"/android/js/devsite_devsite_pagination_module.js"});q.set("devsite-panel",{src:"/android/js/devsite_devsite_panel_module.js"});q.set("devsite-playlist",{src:"/android/js/devsite_devsite_playlist_module.js"});
q.set("devsite-playlist-earnable-badges",{src:"/android/js/devsite_devsite_playlist_earnable_badges_module.js"});q.set("devsite-playlist-summary",{src:"/android/js/devsite_devsite_playlist_summary_module.js"});q.set("devsite-pricing-plans",{src:"/android/js/devsite_devsite_pricing_plans_module.js"});q.set("devsite-product-catalog",{src:"/android/js/devsite_devsite_product_catalog_module.js"});q.set("devsite-profile-card",{src:"/android/js/devsite_devsite_profile_card_module.js"});
q.set("devsite-profile-interests",{src:"/android/js/devsite_devsite_profile_interests_module.js"});q.set("devsite-profile-subscription",{src:"/android/js/devsite_devsite_profile_subscription_module.js"});q.set("devsite-progress",{src:"/android/js/devsite_devsite_progress_module.js"});q.set("devsite-quiz",{src:"/android/js/devsite_devsite_quiz_module.js"});q.set("devsite-recommendations",{src:"/android/js/devsite_devsite_recommendations_module.js"});q.set("devsite-recommendations-dropdown",{src:"/android/js/devsite_devsite_recommendations_dropdown_module.js"});
q.set("devsite-recommendations-sidebar",{src:"/android/js/devsite_devsite_recommendations_sidebar_module.js"});q.set("devsite-recommended-content",{src:"/android/js/devsite_devsite_recommended_content_module.js"});q.set("devsite-reference-results",{src:"/android/js/devsite_devsite_reference_results_module.js"});q.set("devsite-related-entities",{src:"/android/js/devsite_devsite_related_entities_module.js"});q.set("devsite-rich-tooltip",{src:"/android/js/devsite_devsite_rich_tooltip_module.js"});
q.set("devsite-search",{src:"/android/js/devsite_devsite_search_module.js"});q.set("devsite-search-summary",{src:"/android/js/devsite_devsite_search_summary_module.js"});q.set("devsite-select",{src:"/android/js/devsite_devsite_select_module.js"});q.set("devsite-selector",{src:"/android/js/devsite_devsite_selector_module.js"});q.set("devsite-shell",{src:"/android/js/devsite_devsite_shell_module.js"});q.set("devsite-shell-activate-button",{src:"/android/js/devsite_devsite_shell_activate_button_module.js"});
q.set("devsite-sign-in",{src:"/android/js/devsite_devsite_sign_in_module.js"});q.set("devsite-sitemask",{src:"/android/js/devsite_devsite_sitemask_module.js"});q.set("devsite-snackbar",{src:"/android/js/devsite_devsite_snackbar_module.js"});q.set("devsite-sort",{src:"/android/js/devsite_devsite_sort_module.js"});q.set("devsite-spinner",{src:"/android/js/devsite_devsite_spinner_module.js"});q.set("devsite-sticky-nav",{src:"/android/js/devsite_devsite_sticky_nav_module.js"});
q.set("devsite-stripe-checkout",{src:"/android/js/devsite_devsite_stripe_checkout_module.js"});q.set("devsite-support-form",{src:"/android/js/devsite_devsite_support_form_module.js"});q.set("devsite-switch-to-english-button",{src:"/android/js/devsite_devsite_switch_to_english_button_module.js"});q.set("devsite-tabs",{src:"/android/js/devsite_devsite_tabs_module.js"});q.set("devsite-thumb-rating",{src:"/android/js/devsite_devsite_thumb_rating_module.js"});q.set("devsite-toc",{src:"/android/js/devsite_devsite_toc_module.js"});
q.set("devsite-tooltip",{src:"/android/js/devsite_devsite_tooltip_module.js"});q.set("devsite-topic",{src:"/android/js/devsite_devsite_topic_module.js"});q.set("devsite-tracking-question",{src:"/android/js/devsite_devsite_tracking_question_module.js"});q.set("devsite-user",{src:"/android/js/devsite_devsite_user_module.js"});q.set("devsite-var",{src:"/android/js/devsite_devsite_var_module.js"});q.set("devsite-version-selector",{src:"/android/js/devsite_devsite_version_selector_module.js"});
q.set("devsite-video",{src:"/android/js/devsite_devsite_video_module.js"});q.set("devsite-view-release-notes",{src:"/android/js/devsite_devsite_view_release_notes_module.js"});q.set("devsite-view-release-notes-dialog",{src:"/android/js/devsite_devsite_view_release_notes_dialog_module.js"});q.set("devsite-visibility-analytics",{src:"/android/js/devsite_devsite_visibility_analytics_module.js"});q.set("devsite-vplus",{src:"/android/js/devsite_devsite_vplus_module.js"});
q.set("devsite-wall-acknowledgement",{src:"/android/js/devsite_devsite_wall_acknowledgement_module.js"});q.set("devsite-youtube",{src:"/android/js/devsite_devsite_youtube_module.js"});q.set("google-codelab",{src:"/android/js/devsite_google_codelab_module.js"});q.set("google-codelab-about",{src:"/android/js/devsite_google_codelab_about_module.js"});q.set("google-codelab-analytics",{src:"/android/js/devsite_google_codelab_analytics_module.js"});q.set("google-codelab-step",{src:"/android/js/devsite_google_codelab_step_module.js"});
q.set("google-codelab-survey",{src:"/android/js/devsite_google_codelab_survey_module.js"});q.set("android-codelab-grader",{src:"/android/js/devsite_android_codelab_grader_module.js"});q.set("android-fully-clickable",{src:"/android/js/devsite_android_fully_clickable_module.js"});q.set("android-parallax-hero",{src:"/android/js/devsite_android_parallax_hero_module.js"});q.set("android-sticky-lesson",{src:"/android/js/devsite_android_sticky_lesson_module.js"});q.set("android-sticky-toc",{src:"/android/js/devsite_android_sticky_toc_module.js"});
n("DevsiteAppAuthorizedElements",q);n("DevsiteAppTenantCustomized",!0);function ea(a){e.setTimeout(()=>{throw a;},0)};var fa,r;a:{for(var ha=["CLOSURE_FLAGS"],u=e,ia=0;ia<ha.length;ia++)if(u=u[ha[ia]],u==null){r=null;break a}r=u}var ja=r&&r[610401301];fa=ja!=null?ja:!1;var v;const ka=e.navigator;v=ka?ka.userAgentData||null:null;function la(a){return fa?v?v.brands.some(({brand:b})=>b&&b.indexOf(a)!=-1):!1:!1}function w(a){var b;a:{if(b=e.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};function x(){return fa?!!v&&v.brands.length>0:!1}function ma(){return x()?la("Chromium"):(w("Chrome")||w("CriOS"))&&!(x()?0:w("Edge"))||w("Silk")};var na=x()?!1:w("Trident")||w("MSIE");!w("Android")||ma();ma();w("Safari")&&(ma()||(x()?0:w("Coast"))||(x()?0:w("Opera"))||(x()?0:w("Edge"))||(x()?la("Microsoft Edge"):w("Edg/"))||x()&&la("Opera"));var oa={},y=null;var pa=typeof Uint8Array!=="undefined",qa=!na&&typeof btoa==="function";function ra(){const a=Error();a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity="incident";ea(a)};var z=typeof Symbol==="function"&&typeof Symbol()==="symbol",A;A=typeof Symbol==="function"&&typeof Symbol()==="symbol"?Symbol():void 0;var sa=z?(a,b)=>{a[A]|=b}:(a,b)=>{a.o!==void 0?a.o|=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}})},B=z?a=>a[A]|0:a=>a.o|0,ta=z?a=>a[A]:a=>a.o,C=z?(a,b)=>{a[A]=b}:(a,b)=>{a.o!==void 0?a.o=b:Object.defineProperties(a,{o:{value:b,configurable:!0,writable:!0,enumerable:!1}})};var ua={},va={};function wa(a){return!(!a||typeof a!=="object"||a.g!==va)}function D(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)&&a.constructor===Object}function E(a){return!Array.isArray(a)||a.length?!1:B(a)&1?!0:!1}var xa;const ya=[];C(ya,55);xa=Object.freeze(ya);var F=Object.freeze({});var za=typeof e.BigInt==="function"&&typeof e.BigInt(0)==="bigint";const Aa=Number.MIN_SAFE_INTEGER.toString(),Ba=za?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ca=Number.MAX_SAFE_INTEGER.toString(),Da=za?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Ea(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(let c=0;c<a.length;c++){const d=a[c],f=b[c];if(d>f)return!1;if(d<f)return!0}};function Fa(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}function Ga(a){return a==null?a:Number.isFinite(a)?a|0:void 0}function G(a){return a==null||typeof a==="string"?a:void 0};var Na=function(a){H===void 0&&(H=typeof Proxy==="function"?Ha(Proxy):null);if(!H||!Ia())return a;let b=Ja(a);if(b)return b;if(Math.random()>.01)return a;Ka(a);b=new H(a,{set(c,d,f){La();c[d]=f;return!0}});Ma(a,b);return b};function La(){ra()}let I=void 0,Oa=void 0;var Ja=function(a){let b;return(b=I)==null?void 0:b.get(a)};function Ma(a,b){(I||(I=new J)).set(a,b);(Oa||(Oa=new J)).set(b,a)}let H=void 0,J=void 0;function Ia(){J===void 0&&(J=typeof WeakMap==="function"?Ha(WeakMap):null);return J}
function Ha(a){try{return a.toString().indexOf("[native code]")!==-1?a:null}catch(b){return null}}let Pa=void 0;function Ka(a){if(Pa===void 0){const b=new H([],{});Pa=Array.prototype.concat.call([],b).length===1}Pa&&typeof Symbol==="function"&&Symbol.isConcatSpreadable&&(a[Symbol.isConcatSpreadable]=!0)}var Va=function(a,b){const c=Ra(a,b);c&&!Sa(a,c)&&(Ta(),Ua(a,b))};
function Sa(a,b){if(a.length!==b.length)return!1;for(const f in b){var c=Number(f),d;if(d=Number.isInteger(c))d=a[c],c=b[c],d=!(Number.isNaN(d)?Number.isNaN(c):d===c);if(d)return!1}return!0}function Ta(){ra()}let K=void 0;function Ra(a,b){let c,d;return(c=K)==null?void 0:(d=c.get(b))==null?void 0:d.get(a)}var Ua=function(a,b){let c,d;(c=K)==null||(d=c.get(b))==null||d.delete(a)};let L;function Wa(a,b){return Xa(b)}
function Xa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "bigint":return(za?a>=Ba&&a<=Da:a[0]==="-"?Ea(a,Aa):Ea(a,Ca))?Number(a):String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(E(a))return}else if(pa&&a!=null&&a instanceof Uint8Array){if(qa){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{b===void 0&&(b=0);if(!y){y={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");
d=["+/=","+/","-_=","-_.","-_"];for(var f=0;f<5;f++){var g=c.concat(d[f].split(""));oa[f]=g;for(var k=0;k<g.length;k++){var h=g[k];y[h]===void 0&&(y[h]=k)}}}b=oa[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(f=g=0;g<a.length-2;g+=3){var l=a[g],p=a[g+1];h=a[g+2];k=b[l>>2];l=b[(l&3)<<4|p>>4];p=b[(p&15)<<2|h>>6];h=b[h&63];c[f++]=""+k+l+p+h}k=0;h=d;switch(a.length-g){case 2:k=a[g+1],h=b[(k&15)<<2]||d;case 1:a=a[g],c[f]=""+b[a>>2]+b[(a&3)<<4|k>>4]+h+d}a=c.join("")}return a}}return a};function Ya(a,b,c,d,f){if(a!=null){if(Array.isArray(a))a=E(a)?void 0:f&&B(a)&2?a:Za(a,b,c,d!==void 0,f);else if(D(a)){const g={};for(let k in a)g[k]=Ya(a[k],b,c,d,f);a=g}else a=b(a,d);return a}}function Za(a,b,c,d,f){const g=d||c?B(a):0;d=d?!!(g&32):void 0;a=Array.prototype.slice.call(a);for(let k=0;k<a.length;k++)a[k]=Ya(a[k],b,c,d,f);c&&c(g,a);return a}function $a(a){return a.B===ua?a.toJSON():Xa(a)};var M=function(a,b){a=a.g;return ab(a,ta(a),b)},ab=function(a,b,c){if(c===-1)return null;const d=b>>15&1023||536870912;if(c>=d){if(b&256)return a[a.length-1][c]}else return b=c+(+!!(b&512)-1),a=b<0||b>=a.length||b>=d?void 0:a[b],a};
function bb(a,b,c,d){const f=b>>15&1023||536870912;if(c>=f){let g,k=b;if(b&256)g=a[a.length-1];else{if(d==null)return k;g=a[f+(+!!(b&512)-1)]={};k|=256}g[c]=d;c<f&&(a[c+(+!!(b&512)-1)]=void 0);k!==b&&C(a,k);return k}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}
function N(a,b,c,d){var f=a.g,g=ta(f),k=2&g?1:d;d=ab(f,g,b);d=Array.isArray(d)?d:xa;var h=B(d),l=d;Va(l,a);k!==2&&k!==1||Ua(l,a);l=4&h?!1:!0;if(l){4&h&&(d=Array.prototype.slice.call(d),h=cb(h,g),g=bb(f,g,b,d));let t=l=0;for(;l<d.length;l++){const Qa=c(d[l]);Qa!=null&&(d[t++]=Qa)}t<l&&(d.length=t);h===0&&(h=cb(h,g));h|=21;h&=-12289;C(d,h);2&h&&Object.freeze(d)}let p;if(k===1||k===4&&32&h)O(h)||(a=h,h|=2,h!==a&&C(d,h),Object.freeze(d));else if(c=k!==5?!1:!!(32&h)||O(h)||!!Ja(d),(k===2||c)&&O(h)&&(d=
Array.prototype.slice.call(d),h=cb(h,g),h&=-33,C(d,h),g=bb(f,g,b,d)),O(h)||(f=b=h,h=f&=-33,h!==b&&C(d,h)),c){p=Na(d);var m=d;if(Ia()&&!Ra(m,a)&&!(Math.random()>.01)){b=m.length;k={length:b};for(f=0;f<Math.min(b,10);f++)b<=10?g=f:(g=b/10,h=Math.floor(f*g),g=h+Math.floor(Math.random()*(Math.floor((f+1)*g)-h))),k[g]=m[g];Sa(m,k)?(b=K||(K=new J),f=b.get(a),f||(f=new J,b.set(a,f)),f.set(m,k)):(ra(),Ua(m,a))}}else k!==2||(m=I)!=null&&m.delete(d);return p||d}
function O(a){return!!(2&a)&&!!(4&a)||!!(2048&a)}function db(a){a=a.g;let b=ta(a);if(b&2)throw Error();bb(a,b,2,"en")}function cb(a,b){a=2&b?a|2:a&-3;return(a|32)&-2049}function P(a,b){return a!=null?a:b}var Q=function(a,b){return P(G(M(a,b)),"")};let R;var fb=function(){var a=S.config;try{return R=!0,JSON.stringify(eb(a),Wa)}finally{R=!1}},gb=class{constructor(a){a:{a==null&&(a=L);L=void 0;if(a==null){var b=96;a=[]}else{if(!Array.isArray(a))throw Error("narr");b=B(a);if(b&2048)throw Error("farr");if(b&64)break a;var c=a;b|=64;var d=c.length;if(d&&(--d,D(c[d]))){b|=256;c=d-(+!!(b&512)-1);if(c>=1024)throw Error("pvtlmt");b=b&-33521665|(c&1023)<<15}}C(a,b)}this.g=a}toJSON(){return eb(this)}};gb.prototype.B=ua;
gb.prototype.toString=function(){try{return R=!0,eb(this).toString()}finally{R=!1}};
function eb(a){var b;if(a&&(b=K)!=null&&b.has(a)&&(b=a.g))for(var c=0;c<b.length;c++){var d=b[c];if(c===b.length-1&&D(d))for(var f in d){var g=d[f];Array.isArray(g)&&Va(g,a)}else Array.isArray(d)&&Va(d,a)}a=R?a.g:Za(a.g,$a,void 0,void 0,!1);f=!R;if(c=a.length){d=a[c-1];(g=D(d))?c--:d=void 0;b=a;if(g){b:{var k=d;var h;var l=!1;if(k)for(let m in k)if(isNaN(+m)){let t;((t=h)!=null?t:h={})[m]=k[m]}else if(g=k[m],Array.isArray(g)&&(E(g)||wa(g)&&g.size===0)&&(g=null),g==null&&(l=!0),g!=null){let t;((t=
h)!=null?t:h={})[m]=g}l||(h=k);if(h)for(let m in h){l=h;break b}l=null}k=l==null?d!=null:l!==d}for(;c>0;c--){h=b[c-1];if(!(h==null||E(h)||wa(h)&&h.size===0))break;var p=!0}if(b!==a||k||p){if(!f)b=Array.prototype.slice.call(b,0,c);else if(p||k||l)b.length=c;l&&b.push(l)}p=b}else p=a;return p};var hb={oc:0,nc:1,Qb:6,Ob:8,Wb:12,Xb:14,Yb:17,cc:18,ec:21,hc:25,qa:37,ic:38,eb:45,V:47,C:50,N:52,J:62,Na:63,Ib:66,zb:70,D:73,ob:74,Y:75,Fb:76,Ja:77,La:80,K:81,Za:82,Fa:83,xb:85,fa:87,Aa:89,Bb:90,Ba:91,Ka:92,T:93,lc:94,Ea:95,S:96,Jb:97,F:98,H:99,fc:100,xa:101,Ga:102,Eb:103,kc:104,ka:105,U:106,va:107,oa:108,tb:109,ha:110,jc:112,Gb:113,pa:114,ra:116,bb:117,Ya:118,Ca:119,Ab:120,Ub:121,Hb:122,ac:123,Pb:124,Ua:125,pb:126,wa:127,Vb:128,kb:129,lb:130,ta:131,Sa:132,G:133,Oa:134,ya:135,cb:136,I:137,mc:138,
rb:139,Sb:140,Nb:141,jb:142,Wa:143,P:145,nb:146,Pa:147,Va:148,Cb:149,ea:151,Qa:152,dc:156,bc:157,Ma:158,sa:159,L:160,Z:161,la:162,Tb:163,Db:164,ca:166,Kb:167,da:168,Ta:169,Ra:170,Da:171,mb:174,ub:175,vb:176,qb:177,wb:178,Rb:179,Zb:180,aa:181,ja:182,R:183,yb:185,Ha:186,ab:187,ba:188,ia:189,M:191,O:192,Xa:193,Lb:194,za:195,sb:196,ua:197,Mb:198,ib:203,Ia:206,X:207,gb:208,hb:209,W:210,fb:211,ma:212,na:213};var ib=class extends gb{getTenantId(){var a=Ga(M(this,1));return P(a,0)}getLocale(){return Q(this,2)}getInsecureHost(){return Q(this,7)}},jb=function(a){return b=>{if(b==null||b=="")b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("dnarr");sa(b,32);L=b;b=new a(b);L=void 0}return b}}(ib);/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
let kb=globalThis.trustedTypes,lb;function mb(){let a=null;if(!kb)return a;try{const b=c=>c;a=kb.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var nb=class{constructor(a){this.g=a}toString(){return this.g+""}};function ob(a=document){let b,c;a=(c=(b="document"in a?a.document:a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};var pb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),qb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(d>=0){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var T=function(a){this.h=this.u=this.j="";this.v=null;this.s=this.g="";this.m=!1;var b;a instanceof T?(this.m=a.m,rb(this,a.j),this.u=a.u,this.h=a.h,sb(this,a.v),this.g=a.g,tb(this,ub(a.i)),this.s=a.s):a&&(b=String(a).match(pb))?(this.m=!1,rb(this,b[1]||"",!0),this.u=U(b[2]||""),this.h=U(b[3]||"",!0),sb(this,b[4]),this.g=U(b[5]||"",!0),tb(this,b[6]||"",!0),this.s=U(b[7]||"")):(this.m=!1,this.i=new V(null,this.m))};
T.prototype.toString=function(){var a=[],b=this.j;b&&a.push(W(b,vb,!0),":");var c=this.h;if(c||b=="file")a.push("//"),(b=this.u)&&a.push(W(b,vb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.v,c!=null&&a.push(":",String(c));if(c=this.g)this.h&&c.charAt(0)!="/"&&a.push("/"),a.push(W(c,c.charAt(0)=="/"?wb:xb,!0));(c=this.i.toString())&&a.push("?",c);(c=this.s)&&a.push("#",W(c,yb));return a.join("")};
T.prototype.resolve=function(a){var b=new T(this),c=!!a.j;c?rb(b,a.j):c=!!a.u;c?b.u=a.u:c=!!a.h;c?b.h=a.h:c=a.v!=null;var d=a.g;if(c)sb(b,a.v);else if(c=!!a.g){if(d.charAt(0)!="/")if(this.h&&!this.g)d="/"+d;else{var f=b.g.lastIndexOf("/");f!=-1&&(d=b.g.slice(0,f+1)+d)}f=d;if(f==".."||f==".")d="";else if(f.indexOf("./")!=-1||f.indexOf("/.")!=-1){d=f.lastIndexOf("/",0)==0;f=f.split("/");for(var g=[],k=0;k<f.length;){var h=f[k++];h=="."?d&&k==f.length&&g.push(""):h==".."?((g.length>1||g.length==1&&g[0]!=
"")&&g.pop(),d&&k==f.length&&g.push("")):(g.push(h),d=!0)}d=g.join("/")}else d=f}c?b.g=d:c=a.i.toString()!=="";c?tb(b,ub(a.i)):c=!!a.s;c&&(b.s=a.s);return b};
var rb=function(a,b,c){a.j=c?U(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},sb=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.v=b}else a.v=null},tb=function(a,b,c){b instanceof V?(a.i=b,zb(a.i,a.m)):(c||(b=W(b,Ab)),a.i=new V(b,a.m))},Bb=function(a){return a instanceof T?new T(a):new T(a)},U=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Cb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Cb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},vb=/[#\/\?@]/g,xb=/[#\?:]/g,wb=/[#\?]/g,Ab=/[#\?@]/g,yb=/#/g,V=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.i&&qb(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};V.prototype.add=function(a,b){X(this);this.i=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
V.prototype.remove=function(a){X(this);a=Y(this,a);return this.g.has(a)?(this.i=null,this.h-=this.g.get(a).length,this.g.delete(a)):!1};V.prototype.clear=function(){this.g=this.i=null;this.h=0};var Db=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};V.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,d){c.forEach(function(f){a.call(b,f,d,this)},this)},this)};
var Eb=function(a,b){X(a);let c=[];if(typeof b==="string")Db(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};V.prototype.set=function(a,b){X(this);this.i=null;a=Y(this,a);Db(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};V.prototype.get=function(a,b){if(!a)return b;a=Eb(this,a);return a.length>0?String(a[0]):b};
V.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var d=b[c];const g=encodeURIComponent(String(d)),k=Eb(this,d);for(d=0;d<k.length;d++){var f=g;k[d]!==""&&(f+="="+encodeURIComponent(String(k[d])));a.push(f)}}return this.i=a.join("&")};
var ub=function(a){var b=new V;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},Y=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},zb=function(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,d){var f=d.toLowerCase();if(d!=f&&(this.remove(d),this.remove(f),c.length>0)){this.i=null;d=this.g;var g=d.set;f=Y(this,f);var k=c.length;if(k>0){const h=Array(k);for(let l=0;l<k;l++)h[l]=c[l];k=h}else k=[];g.call(d,f,k);this.h+=c.length}},a));a.j=b};const Fb={};function Gb(a,b){var c=Fb[a];if(c!==void 0&&(!c.A||Date.now()<=c.A+3E5))return c.p;c=new Promise((f,g)=>{b.onload=()=>f(b);b.onerror=k=>{b.parentNode&&b.parentNode.removeChild(b);g(k)};document.head.appendChild(b)});const d={A:0,p:c};c.catch(()=>d.A=+new Date);Fb[a]=d;return c}
var Hb=function(a){a=Bb(a);const b=document.createElement("script");var c=a.toString();c=c===null?"null":c===void 0?"undefined":c;lb===void 0&&(lb=mb());var d=lb;c=new nb(d?d.createScriptURL(c):c);if(c instanceof nb)c=c.g;else throw Error("");b.src=c;(c=ob(b.ownerDocument&&b.ownerDocument.defaultView||window))&&b.setAttribute("nonce",c);return Gb(a.toString(),b)};class Ib{constructor(){this.promise=new Promise((a,b)=>{this.resolve=a;this.reject=b})}};var Z=function(a="Devsite has failed to load."){document.documentElement.removeAttribute("cached");console.error(a)},Kb=async function(){var a=S;const b=new Ib;n("__devsiteAppReadyResolver",b.resolve);n("__devsiteAppReadyPromise",b.promise);n("DevsiteApp.whenReady",()=>b.promise);if(N(a.config,12,G,void 0===F?2:5).length)try{await Promise.all(N(a.config,12,G,void 0===F?2:5).map(f=>{f=Bb(f);const g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");
g.setAttribute("href",f.toString());return Gb(f.toString(),g)}))}catch(f){Z(`Failed to load Devsite App dependencies: ${f.message}`);return}const c=e.DevsiteAppTenantCustomized?Q(a.config,6):Q(a.config,5);try{await Hb(`${c}${Jb(a)}`)}catch(f){if(a.config.getLocale()!=="en"){db(a.config);try{await Hb(`${c}${Q(a.config,4)}`)}catch(g){Z(`Failed to load Devsite App binary: ${g.message}`);return}}else{Z(`Failed to load Devsite App binary: ${f.message}`);return}}const d=document;if(d.readyState!=="complete"&&
d.readyState!=="interactive"){const f=new Ib;d.addEventListener("readystatechange",()=>{d.readyState!=="interactive"&&d.readyState!=="complete"||f.resolve()});await f.promise}},Jb=function(a){const b=a.config.getLocale();a=Q(a.config,4);return b&&b!=="en"?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const S=new class{constructor(){this.g=null;this.config=new ib;this.h=[];this.i=a=>{this.h.push(a)};this.m=()=>{this.j()};if(e.__globalAppLoader)return e.__globalAppLoader;try{this.config=jb(`${GoogleDevelopersObject}`.replaceAll("\n",""))}catch(a){Z("GoogleDevelopersObject missing or invalid");return}GoogleDevelopersObject=null;n("__globalAppLoader",this);n("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a));n("DevsiteApp.hasMendelFlagAccess",(a,b)=>this.hasMendelFlagAccess(a,b))}j(){var a=document.querySelector("devsite-content");
a&&(window.removeEventListener("message",this.i),a.removeEventListener("devsite-content-updated",this.m));a=window;for(const b of this.h)a.dispatchEvent(b);this.h=[]}getEnv(){if(P(Fa(M(this.config,11)),!1))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){var b=this.getEnv();
var c=N(this.config,13,Ga,F===F?2:5);a:{var d=new URL(document.location.toString());d=new T(d.href);const f=Object.keys(hb);if(b!=="PROD")for(const g of f)if(hb[g]===a&&(b=d.i.get(g),b!==void 0)){a=b==="true";break a}a=Array.from(c).includes(a)}return a}hasMendelFlagAccess(a,b){var c=this.getEnv();var d=N(this.config,22,G,F===F?2:5);a:{var f=new URL(document.location.toString());f=new T(f.href);a=a+"__"+b;if(c!=="PROD"&&(c=f.i.get(a),c!==void 0)){d=c==="true";break a}d=Array.from(d).includes(a)}return d}},
Lb=document.querySelector("devsite-content");Lb&&(window.addEventListener("message",S.i),Lb.addEventListener("devsite-content-updated",S.j.bind(S)));(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return S.g||(S.g=Kb()),S.g})().then(()=>{P(Fa(M(S.config,9)),!1)?e.DevsiteAppFrameboxInit?DevsiteAppFrameboxInit(fb(),e.DevsiteAppAuthorizedElements):Z("Failed to load Devsite App binary"):e.DevsiteAppInit?DevsiteAppInit(fb(),e.DevsiteAppAuthorizedElements):Z("Failed to load Devsite App binary")});}).call(this);
